-- Drop helpers (ignore errors if not exist)
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE order_items CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE stage_orders_csv CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP TABLE load_errors CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_orders'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_order_items'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_customers'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /
-- BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE seq_products'; EXCEPTION WHEN OTHERS THEN NULL; END;
-- /

-- CLEAR TABLES FROM SCHEMA
DECLARE
  CURSOR all_tables IS
    select table_name from user_tables;
BEGIN
  FOR i IN all_tables
  LOOP
    BEGIN
      EXECUTE IMMEDIATE 'DROP TABLE '||i.table_name||' CASCADE CONSTRAINTS PURGE';
    EXCEPTION
      WHEN OTHERS THEN
        NULL;
    END;
  END LOOP;
END;
/

-- Core tables
CREATE TABLE customers(
  customer_id NUMBER PRIMARY KEY,
  email       VARCHAR2(320) UNIQUE,
  full_name   VARCHAR2(200),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at  TIMESTAMP
);

CREATE TABLE products(
  product_id  NUMBER PRIMARY KEY,
  sku         VARCHAR2(64) UNIQUE,
  name        VARCHAR2(200),
  price_cents NUMBER(10),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at  TIMESTAMP
);

CREATE TABLE orders(
  order_id    NUMBER PRIMARY KEY,
  customer_id NUMBER NOT NULL REFERENCES customers(customer_id),
  order_ts    TIMESTAMP NOT NULL,
  total_cents NUMBER(12),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE order_items(
  order_item_id NUMBER PRIMARY KEY,
  order_id      NUMBER NOT NULL REFERENCES orders(order_id),
  product_id    NUMBER NOT NULL REFERENCES products(product_id),
  qty           NUMBER NOT NULL,
  unit_cents    NUMBER(10) NOT NULL
);

-- Staging (think: CSV already loaded by external tool)
CREATE TABLE stage_orders_csv(
  batch_id       NUMBER NOT NULL,
  row_num        NUMBER NOT NULL,
  customer_email VARCHAR2(320),
  customer_name  VARCHAR2(200),
  product_sku    VARCHAR2(64),
  product_name   VARCHAR2(200),
  unit_cents     NUMBER(10),
  qty            NUMBER,
  order_ts       TIMESTAMP,
  CONSTRAINT pk_stage PRIMARY KEY (batch_id, row_num)
);

-- Error log (autonomous logging target)
CREATE TABLE load_errors(
  id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  op          VARCHAR2(30),
  batch_id    NUMBER,
  row_num     NUMBER,
  code        NUMBER,
  msg         VARCHAR2(4000),
  created_at  TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Sequences (simple for demo)
CREATE SEQUENCE seq_customers START WITH 1;
CREATE SEQUENCE seq_products START WITH 1;
CREATE SEQUENCE seq_orders START WITH 1;
CREATE SEQUENCE seq_order_items START WITH 1;

